### ISSUE TITLE
create first check

### ISSUE THREAD

**Issue by satoknj** [gk0909c/chapex#1]
first check is below

+ [x] class name start camel_case
+ [x] method name camel_case
+ [x] field name camel_case
+ [x] field name camel_case when field is constant
    + astのtypeを「name」とかにして、childrenから指定タイプを検索（find）する必要あり
    + [x] fieldタイプノード配下のnameノードのタイプをnameに変更
    + [x] ノードにchildrenからtypeでfindする処理を追加
    + [x] チェック処理に反映 
    + [x] fieldノード配下にfinalノードを追加
    + [x] フィールド名チェック処理でfinalがついてるかを加味する（ノードにhas?メソッドが必要）
    + [x] 定数の場合のチェックロジックも追加
    + [x] リファクタリング 
+ [x] variable name camel_case
+ [x] basic indentation check

**Comment by gk0909c** [comment]
rough design

![chapex_class_diagram](https://user-images.githubusercontent.com/12490209/28911473-946ead00-786b-11e7-89b8-e3ba024181c6.jpg)

**Comment by gk0909c** [comment]
my memo

1. astフォルダを作る。builderはそこに移動する。nodeの継承クラスを作る
2. 木をどうやって作るか考える。もう少しrubocopを参考にする
3. 2の結果によるが、nodeにpropsをつけてチェックする側で位置を参照する
    + これのやり方もrubocopを参考に

**Comment by satoknj** [comment]
色々な構文に対応しておく必要はある  
構文木の定義が変わるとチェック処理に影響が出るので、先にこっちをやった方がよい

+ [x] クラス修飾子
+ [x] メソッド修飾子
+ [x] フィールド修飾子
+ [x] フィールド宣言と代入
+ [x] ローカル変数代入（宣言あり、宣言なし）
+ [x] if文
+ [x] for文
+ [x] for-each文
+ [x] while文

**Comment by satoknj** [comment]
後は構文エラーになった場合に無視できれば最初の機能としてはいい気がする
